defaults:
  - _base

decompose_key_query_value: false
decompose_output_projection: false
decompose_ff_and_proj: true
decompose_embedding_layer: false
decompose_un_embedding_layer: false
key_query_value:
  _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
  in_channels: 576
  out_channels: 576
  out_shape: [9, 64]
  number_cores: 2
  compression_factor: ${oc.select:equal_compression_factor,1}
  min_ranks: 10
  topology: btt
causal_attention_projection:
  _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
  in_channels: 576
  out_channels: 576
  in_shape: [9, 64]
  number_cores: 2
  compression_factor: ${oc.select:equal_compression_factor,1}
  min_ranks: 8
  topology: btt
key:
  _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
  in_channels: 576
  out_channels: 192
  out_shape: [3, 64]
  number_cores: 2
  compression_factor: ${oc.select:equal_compression_factor,1}
  min_ranks: 10
  topology: btt
query:
  _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
  in_channels: 576
  out_channels: 576
  out_shape: [9, 64]
  number_cores: 2
  compression_factor: ${oc.select:equal_compression_factor,1}
  min_ranks: 10
  topology: btt
value:
  _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
  in_channels: 576
  out_channels: 192
  out_shape: [3, 64]
  number_cores: 2
  compression_factor: ${oc.select:equal_compression_factor,1}
  min_ranks: 10
  topology: btt
mlp:
  _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
  in_channels: 576
  out_channels: 1536
  number_cores: 2
  compression_factor: ${oc.select:equal_compression_factor,1}
  min_ranks: 10
  topology: btt
mlp_gate:
  _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
  in_channels: 576
  out_channels: 1536
  number_cores: 2
  compression_factor: ${oc.select:equal_compression_factor,1}
  min_ranks: 10
  topology: btt
mlp_projection:
  _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
  in_channels: 1536
  out_channels: 576
  number_cores: 2
  compression_factor: ${oc.select:equal_compression_factor,1}
  min_ranks: 10
  topology: btt
decompose_algorithm:
  _target_: percipio2.skiboot.td.base.decompose_methods.decompose_with_btt_svd
init_scale_exponent: 2 # empirically found to give the best quality
