# @package model.config.percipio.tensor_decomposition

defaults:
  - /tensor_decomposition_base

rules: # rules are in order from most general to most specific
  query:
    find:
      pattern: model\.layers\.\b([3-9]|[1][0-9]|[2][0-3])\b\.self_attn\.q_proj   # 3-23
    general_replace:
      solver_method:
        _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
        _partial_: true
        number_cores: 2
        compression_factor: ${oc.select:equal_compression_factor,1}
        min_ranks: 10
        topology: ${oc.select:same_topology,btt}
        out_shape: [14, 64]
      decompose: true
  key:
    find:
      pattern: model\.layers\.\b([3-9]|[1][0-9]|[2][0-3])\b\.self_attn\.k_proj   # 3-23
    general_replace:
      solver_method:
        _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
        _partial_: true
        number_cores: 2
        compression_factor: ${oc.select:equal_compression_factor,1}
        min_ranks: 10
        topology: ${oc.select:same_topology,btt}
        out_shape: [2, 64]
      decompose: true
  value:
    find:
      pattern: model\.layers\.\b([1][5-9]|[2][0-3])\b\.self_attn\.v_proj
    general_replace:
      solver_method:
        _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
        _partial_: true
        number_cores: 2
        compression_factor: ${oc.select:equal_compression_factor,1}
        min_ranks: 10
        topology: ${oc.select:same_topology,btt}
        out_shape: [2, 64]
      decompose: true
  causal_attention_projection:
    find:
      pattern: model\.layers\.\b([1][5-9]|[2][0-3])\b.self_attn\.o_proj
    general_replace:
      solver_method:
        _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
        _partial_: true
        number_cores: 2
        compression_factor: ${oc.select:equal_compression_factor,1}
        min_ranks: 10
        topology: ${oc.select:same_topology,btt}
        in_shape: [14, 64]
      decompose: true
  mlp_up_proj:
    find:
      pattern: model\.layers\.\b([7-9]|[1][0-9]|[2][0-3])\b\.mlp\.up_proj
    general_replace:
      solver_method:
        _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
        _partial_: true
        number_cores: 2
        compression_factor: ${oc.select:equal_compression_factor,1}
        min_ranks: 10
        topology: ${oc.select:same_topology,btt}
      decompose: true
  mlp_down_proj:
    find:
      pattern: model\.layers\.\b([1][5-9]|[2][0-3])\b\.mlp\.down_proj
    general_replace:
      solver_method:
        _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
        _partial_: true
        number_cores: 2
        compression_factor: ${oc.select:equal_compression_factor,1}
        min_ranks: 10
        topology: ${oc.select:same_topology,btt}
      decompose: true
  mlp_gate_proj:
    find:
      pattern: model\.layers\.\b([7-9]|1[0-9]|2[0-3])\b\.mlp\.gate_proj
    general_replace:
      solver_method:
        _target_: percipio2.skiboot.td.config.Decomposition.solve_low_ecf
        _partial_: true
        number_cores: 2
        compression_factor: ${oc.select:equal_compression_factor,1}
        min_ranks: 10
        topology: ${oc.select:same_topology,btt}
      decompose: true
